// Kun SidebarClawDialog.tsx visual port — add/manage IM connection modal.
// Visual only: mock snapshots and preview URL hooks.

import {
  useMemo,
  useState,
  type ReactElement,
} from 'react'
import {
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Copy,
  Eye,
  EyeOff,
  Loader2,
  MessageSquare,
  QrCode,
  Settings,
  Trash2,
  X,
} from 'lucide-react'
import {
  CLAW_SIDEBAR_PRODUCTION_CHANNELS,
  ClawProviderLogo,
  clawProviderDisplayLabel,
  type ClawImChannelSidebarSnapshot,
  type ClawImProvider,
} from './ClawSidebar'

export type ClawDialogStep = 'defaults' | 'prompt' | 'connection'
export type ClawImDialogMode = 'add' | 'edit'
export type ClawManageStage = 'select' | 'configure'
export type ClawInstallTarget = 'feishu' | 'lark' | 'weixin'
export type ClawInstallQrStatus = 'idle' | 'loading' | 'showing' | 'success' | 'error'

export type ClawAddImDialogPreviewMode =
  | 'add'
  | 'prompt'
  | 'connection'
  | 'qrLoading'
  | 'qrShowing'
  | 'qrSuccess'
  | 'qrError'
  | 'manage'
  | 'edit'
  | 'empty'
  | 'manageEmpty'
  | 'busy'
  | 'error'

type ClawAgentProfile = {
  name: string
  description: string
  identity: string
  personality: string
  userContext: string
  replyRules: string
}

type ProviderOption = {
  id: ClawImProvider
  label: string
  tone: 'feishu' | 'weixin'
  guideSteps: string[]
}

const DIALOG_STEPS: Array<{
  id: ClawDialogStep
  label: string
  description: string
  icon: typeof Settings
}> = [
  {
    id: 'defaults',
    label: 'Connection defaults',
    description: 'Name, model, and workspace',
    icon: Settings,
  },
  {
    id: 'prompt',
    label: 'Agent prompt',
    description: 'Identity, persona, context, and reply rules',
    icon: MessageSquare,
  },
  {
    id: 'connection',
    label: 'Connection setup',
    description: 'Official QR, connection status, and advanced settings',
    icon: QrCode,
  },
]

const AGENT_TABS: Array<{
  id: keyof Pick<
    ClawAgentProfile,
    'identity' | 'personality' | 'userContext' | 'replyRules'
  >
  label: string
  helper: string
  placeholder: string
}> = [
  {
    id: 'identity',
    label: 'Identity',
    helper: 'Define who this IM Agent is, including role, scope, capabilities, and boundaries.',
    placeholder:
      'Example: You are a development assistant in the project chat. Explain code, organize tasks, and flag risks.',
  },
  {
    id: 'personality',
    label: 'Personality',
    helper: 'Define tone, expression style, patience, and whether it should ask follow-up questions.',
    placeholder:
      'Example: Be concise, professional, and direct. State assumptions when information is uncertain.',
  },
  {
    id: 'userContext',
    label: 'About you',
    helper: 'Add persistent user, team, or preference context this Agent should remember.',
    placeholder:
      'Example: The user coordinates product and engineering, prefers Chinese, short conclusions, and action lists.',
  },
  {
    id: 'replyRules',
    label: 'Reply rules',
    helper: 'Define response format, length, step style, and risk-confirmation rules.',
    placeholder:
      'Example: Start with the answer, then explain why. List impact when commands or code changes are involved.',
  },
]

const PROVIDER_OPTIONS: ProviderOption[] = [
  {
    id: 'feishu',
    label: 'Feishu / Lark',
    tone: 'feishu',
    guideSteps: [
      'Choose Feishu or Lark, generate an official QR, then scan it with the matching client to authorize a PersonalAgent app.',
      'After scanning, polling returns appId/appSecret. They are saved locally and never written into the QR.',
      'After binding, the desktop app uses these credentials to connect to Feishu / Lark directly. If you also run a custom relay, you can still forward messages to the local endpoint.',
    ],
  },
  {
    id: 'weixin',
    label: 'WeChat',
    tone: 'weixin',
    guideSteps: [
      "WeChat scanning is generated by Kun's WeChat login service and uses the real WeChat authorization flow.",
      'After confirmation on the phone, the desktop app waits for authorization and stores the returned WeChat account binding locally.',
      'After binding, WeChat and Feishu/Lark can coexist in the sidebar; WeChat messages enter the matching phone Agent conversation.',
    ],
  },
]

const PREVIEW_CHANNELS: ClawImChannelSidebarSnapshot[] = [
  {
    id: 'feishu-team',
    provider: 'feishu',
    label: 'Team Feishu',
    enabled: true,
    model: 'auto',
    threadId: 'thread-feishu-1',
    updatedAt: '2026-06-22T12:00:00.000Z',
    conversations: [],
  },
  {
    id: 'weixin-support',
    provider: 'weixin',
    label: 'WeChat Support',
    enabled: true,
    model: 'deepseek-v4-pro',
    threadId: '',
    updatedAt: '2026-06-21T18:30:00.000Z',
    conversations: [],
  },
]

const DEFAULT_WORKSPACE_PREVIEW = '~/.kun/claw/feishu/feishu/<appId-or-channel-id>'

const MOCK_BINDING_PAYLOAD = `{
  "endpoint": "http://127.0.0.1:8787/claw/im",
  "provider": "feishu",
  "agentName": "feishu agent",
  "secret": ""
}`

function installTargetLabel(target: ClawInstallTarget): string {
  if (target === 'weixin') return 'WeChat'
  return target === 'lark' ? 'Lark' : 'Feishu'
}

function MockQrCode(): ReactElement {
  return (
    <svg viewBox="0 0 48 48" className="claw-add-im-mock-qr" aria-hidden="true">
      <rect width="48" height="48" fill="#fff" />
      <rect x="4" y="4" width="12" height="12" fill="#111" />
      <rect x="32" y="4" width="12" height="12" fill="#111" />
      <rect x="4" y="32" width="12" height="12" fill="#111" />
      {Array.from({ length: 64 }, (_, index) => {
        const row = Math.floor(index / 8)
        const col = index % 8
        if ((row < 2 && col < 2) || (row < 2 && col > 5) || (row > 5 && col < 2)) return null
        if ((row + col + index) % 3 === 0) {
          return (
            <rect
              key={index}
              x={16 + col * 2}
              y={16 + row * 2}
              width="2"
              height="2"
              fill="#111"
            />
          )
        }
        return null
      })}
    </svg>
  )
}

function ToggleSwitch({
  checked,
  onChange,
  ariaLabel,
}: {
  checked: boolean
  onChange: (next: boolean) => void
  ariaLabel: string
}): ReactElement {
  return (
    <button
      type="button"
      className={`claw-add-im-toggle${checked ? ' is-on' : ''}`}
      aria-label={ariaLabel}
      aria-pressed={checked}
      onClick={() => onChange(!checked)}
    >
      <span className="claw-add-im-toggle-thumb" />
    </button>
  )
}

type DialogViewProps = {
  mode: ClawImDialogMode
  manageStage: ClawManageStage
  activeStep: ClawDialogStep
  provider: ClawImProvider
  channels: ClawImChannelSidebarSnapshot[]
  selectedChannelId: string
  agentProfile: ClawAgentProfile
  channelModel: string
  channelEnabled: boolean
  channelWorkspaceRoot: string
  officialInstallTarget: ClawInstallTarget
  advancedOpen: boolean
  imEnabled: boolean
  runMode: string
  imPort: number
  imPath: string
  responseTimeoutSec: number
  secret: string
  showSecret: boolean
  endpoint: string
  copied: boolean
  installQrStatus: ClawInstallQrStatus
  installQrTimeLeft: number
  installQrUserCode: string
  installQrError: string
  error: string | null
  loadingConfig: boolean
  busy: boolean
  onClose: () => void
  onSelectStep: (step: ClawDialogStep) => void
  onEnterManageConfigure: (channelId: string) => void
  onReturnToManageSelection: () => void
  onUpdateAgentProfile: (patch: Partial<ClawAgentProfile>) => void
  onSetChannelModel: (value: string) => void
  onSetChannelEnabled: (value: boolean) => void
  onSetChannelWorkspaceRoot: (value: string) => void
  onSetOfficialInstallTarget: (value: ClawInstallTarget) => void
  onSetAdvancedOpen: (value: boolean) => void
  onSetImEnabled: (value: boolean) => void
  onSetRunMode: (value: string) => void
  onSetImPort: (value: number) => void
  onSetImPath: (value: string) => void
  onSetResponseTimeoutSec: (value: number) => void
  onSetSecret: (value: string) => void
  onToggleShowSecret: () => void
  onCopyBinding: () => void
  onGenerateQr: () => void
  onPrevStep: () => void
  onPrimaryAction: () => void
}

function ClawAddImDialogView(props: DialogViewProps): ReactElement {
  const {
    mode,
    manageStage,
    activeStep,
    provider,
    channels,
    selectedChannelId,
    agentProfile,
    channelModel,
    channelEnabled,
    channelWorkspaceRoot,
    officialInstallTarget,
    advancedOpen,
    imEnabled,
    runMode,
    imPort,
    imPath,
    responseTimeoutSec,
    secret,
    showSecret,
    endpoint,
    copied,
    installQrStatus,
    installQrTimeLeft,
    installQrUserCode,
    installQrError,
    error,
    loadingConfig,
    busy,
    onClose,
    onSelectStep,
    onEnterManageConfigure,
    onReturnToManageSelection,
    onUpdateAgentProfile,
    onSetChannelModel,
    onSetChannelEnabled,
    onSetChannelWorkspaceRoot,
    onSetOfficialInstallTarget,
    onSetAdvancedOpen,
    onSetImEnabled,
    onSetRunMode,
    onSetImPort,
    onSetImPath,
    onSetResponseTimeoutSec,
    onSetSecret,
    onToggleShowSecret,
    onCopyBinding,
    onGenerateQr,
    onPrevStep,
    onPrimaryAction,
  } = props

  const selectedOption =
    PROVIDER_OPTIONS.find((option) => option.id === provider) ?? PROVIDER_OPTIONS[0]
  const existingChannel =
    mode === 'edit'
      ? channels.find((channel) => channel.id === selectedChannelId) ?? null
      : null
  const activeStepIndex = DIALOG_STEPS.findIndex((step) => step.id === activeStep)
  const activeStepConfig = DIALOG_STEPS[activeStepIndex] ?? DIALOG_STEPS[0]
  const atLastStep = activeStepIndex >= DIALOG_STEPS.length - 1
  const isManageSelection = mode === 'edit' && manageStage === 'select'
  const showEmptyState =
    mode === 'edit' ? channels.length === 0 : channels.length >= PROVIDER_OPTIONS.length
  const installTargets: ClawInstallTarget[] =
    provider === 'weixin' ? ['weixin'] : ['feishu', 'lark']

  const dialogTitle = mode === 'edit' ? 'Manage IM connections' : 'Add IM'
  const dialogSubtitle =
    mode === 'edit'
      ? 'This dialog only edits IM connections that are already in the sidebar. It does not create new bindings.'
      : 'Phone connection supports one Feishu/Lark connection and one WeChat connection. Set connection defaults first, then the Agent prompt, then finish QR setup.'
  const providerListTitle = mode === 'edit' ? 'Connected' : 'Integration'
  const primaryActionLabel = isManageSelection
    ? 'Edit settings'
    : atLastStep
      ? mode === 'edit'
        ? busy
          ? 'Saving'
          : 'Save settings'
        : busy
          ? 'Adding'
          : 'Bind and add'
      : 'Next'

  return (
    <div className="claw-add-im-dialog-overlay">
      <div className="claw-add-im-dialog" role="dialog" aria-modal="true">
        <header className="claw-add-im-dialog-header">
          <div className="claw-add-im-dialog-heading">
            <div className="claw-add-im-dialog-title-row">
              <QrCode className="claw-add-im-dialog-title-icon" strokeWidth={1.9} />
              <h2 className="claw-add-im-dialog-title">{dialogTitle}</h2>
            </div>
            <p className="claw-add-im-dialog-subtitle">{dialogSubtitle}</p>
          </div>
          <button
            type="button"
            className="claw-add-im-dialog-close"
            onClick={onClose}
            aria-label="Close"
            title="Close"
          >
            <X className="claw-add-im-dialog-close-icon" strokeWidth={1.9} />
          </button>
        </header>

        <div className="claw-add-im-dialog-body">
          <div className="claw-add-im-dialog-inner">
            {showEmptyState ? (
              <div className="claw-add-im-empty-panel">
                <div className="claw-add-im-empty-title">
                  {mode === 'edit'
                    ? 'No connection has been added yet'
                    : 'No new connection is available'}
                </div>
                <p className="claw-add-im-empty-desc">
                  {mode === 'edit'
                    ? 'Bind an IM connection from the add dialog first, then come back here to edit its configuration.'
                    : 'All currently supported IM connections have already been added. Close this dialog and use the settings button to manage the existing one.'}
                </p>
              </div>
            ) : isManageSelection ? (
              <div className="claw-add-im-panel">
                <div className="claw-add-im-panel-head">
                  <div className="claw-add-im-panel-head-copy">
                    <div className="claw-add-im-kicker">{providerListTitle}</div>
                    <div className="claw-add-im-panel-title">Choose an IM connection to manage</div>
                    <p className="claw-add-im-panel-desc">
                      Pick one connected IM first, then edit its Agent name, persona, model, and workspace.
                    </p>
                  </div>
                  {loadingConfig ? (
                    <div className="claw-add-im-loading-pill">
                      <Loader2 className="claw-add-im-loading-icon is-spin" strokeWidth={2} />
                      Loading…
                    </div>
                  ) : null}
                </div>
                <div className="claw-add-im-manage-grid">
                  {channels.map((channel) => {
                    const active = channel.id === selectedChannelId
                    const option =
                      PROVIDER_OPTIONS.find((item) => item.id === channel.provider) ??
                      PROVIDER_OPTIONS[0]
                    return (
                      <div
                        key={channel.id}
                        className={`claw-add-im-manage-card${active ? ' is-active' : ''}`}
                      >
                        <button
                          type="button"
                          className="claw-add-im-manage-card-main"
                          onClick={() => onEnterManageConfigure(channel.id)}
                        >
                          <span
                            className={`claw-add-im-provider-badge is-${option.tone}`}
                          >
                            <ClawProviderLogo provider={channel.provider} className="claw-add-im-provider-badge-logo" />
                          </span>
                          <span className="claw-add-im-manage-card-copy">
                            <span className="claw-add-im-manage-card-title">{channel.label}</span>
                            <span className="claw-add-im-manage-card-meta">
                              {clawProviderDisplayLabel(channel.provider)} · {channel.model}
                            </span>
                            <span className="claw-add-im-manage-card-status">
                              {channel.enabled ? 'Enabled' : 'Disabled'}
                            </span>
                          </span>
                          <ChevronRight className="claw-add-im-manage-card-chevron" strokeWidth={1.9} />
                        </button>
                        <button
                          type="button"
                          className="claw-add-im-manage-delete"
                          aria-label="Delete IM"
                          title="Delete IM"
                        >
                          <Trash2 className="claw-add-im-manage-delete-icon" strokeWidth={1.9} />
                        </button>
                      </div>
                    )
                  })}
                </div>
              </div>
            ) : (
              <>
                <div className="claw-add-im-panel">
                  <div className="claw-add-im-panel-head">
                    {mode === 'edit' ? (
                      <div className="claw-add-im-edit-head">
                        <button
                          type="button"
                          className="claw-add-im-back-btn"
                          onClick={onReturnToManageSelection}
                          aria-label="Back to connection list"
                          title="Back to connection list"
                        >
                          <ArrowLeft className="claw-add-im-back-icon" strokeWidth={1.9} />
                        </button>
                        <div className="claw-add-im-edit-head-copy">
                          <div className="claw-add-im-kicker">Editing</div>
                          <div className="claw-add-im-panel-title">
                            {existingChannel?.label ?? selectedOption.label}
                          </div>
                          <div className="claw-add-im-edit-meta">
                            {clawProviderDisplayLabel(provider)} · {channelModel}
                          </div>
                        </div>
                      </div>
                    ) : (
                      <div className="claw-add-im-setup-head">
                        <span className={`claw-add-im-provider-badge is-${selectedOption.tone} is-large`}>
                          <ClawProviderLogo provider={provider} className="claw-add-im-provider-badge-logo" />
                        </span>
                        <div className="claw-add-im-setup-head-copy">
                          <div className="claw-add-im-kicker">Setup flow</div>
                          <div className="claw-add-im-panel-title">{selectedOption.label}</div>
                          <div className="claw-add-im-edit-meta">Ready to generate an official QR</div>
                        </div>
                      </div>
                    )}
                    {loadingConfig ? (
                      <div className="claw-add-im-loading-pill">
                        <Loader2 className="claw-add-im-loading-icon is-spin" strokeWidth={2} />
                        Loading…
                      </div>
                    ) : null}
                  </div>
                  <div className="claw-add-im-step-pills">
                    {DIALOG_STEPS.map((step, index) => {
                      const Icon = step.icon
                      const active = activeStep === step.id
                      const completed = index < activeStepIndex
                      return (
                        <button
                          key={step.id}
                          type="button"
                          className={`claw-add-im-step-pill${active ? ' is-active' : ''}`}
                          onClick={() => onSelectStep(step.id)}
                        >
                          <span
                            className={`claw-add-im-step-index${
                              active ? ' is-active' : completed ? ' is-complete' : ''
                            }`}
                          >
                            {completed ? (
                              <CheckCircle2 className="claw-add-im-step-check" strokeWidth={1.9} />
                            ) : (
                              index + 1
                            )}
                          </span>
                          <Icon className="claw-add-im-step-icon" strokeWidth={1.9} />
                          <span>{step.label}</span>
                        </button>
                      )
                    })}
                  </div>
                </div>

                <div className="claw-add-im-panel">
                  <div className="claw-add-im-panel-head">
                    <div className="claw-add-im-setup-head">
                      <span className={`claw-add-im-provider-badge is-${selectedOption.tone} is-xl`}>
                        <ClawProviderLogo provider={provider} className="claw-add-im-provider-badge-logo is-xl" />
                      </span>
                      <div className="claw-add-im-setup-head-copy">
                        <div className="claw-add-im-panel-title is-large">{selectedOption.label}</div>
                        <div className="claw-add-im-edit-meta">
                          {mode === 'edit'
                            ? 'You are editing an existing connection'
                            : 'Ready to generate an official QR'}
                        </div>
                      </div>
                    </div>
                    <div className="claw-add-im-step-counter-wrap">
                      <span className="claw-add-im-step-counter">
                        Step {activeStepIndex + 1} / {DIALOG_STEPS.length}
                      </span>
                    </div>
                  </div>
                  <div className="claw-add-im-active-step-chip">
                    <span className="claw-add-im-active-step-label">{activeStepConfig.label}</span>
                    <span>·</span>
                    <span>{activeStepConfig.description}</span>
                  </div>

                  {mode === 'edit' ? (
                    <div className="claw-add-im-summary-grid">
                      <div className="claw-add-im-summary-card">
                        <div className="claw-add-im-summary-kicker">Connection</div>
                        <div className="claw-add-im-summary-title">Connected</div>
                        <div className="claw-add-im-summary-desc">Connection method</div>
                      </div>
                      <div className="claw-add-im-summary-card">
                        <div className="claw-add-im-summary-kicker">Credentials</div>
                        <div className="claw-add-im-summary-title">
                          {installQrStatus === 'success'
                            ? 'Scan succeeded'
                            : 'Generate official QR'}
                        </div>
                        <div className="claw-add-im-summary-desc">
                          {installQrStatus === 'success'
                            ? 'The platform binding was obtained and will be saved locally with this connection.'
                            : 'Complete the official QR authorization before binding and adding.'}
                        </div>
                      </div>
                      <div className="claw-add-im-summary-card">
                        <div className="claw-add-im-summary-kicker">Local endpoint</div>
                        <div className="claw-add-im-summary-mono">{endpoint}</div>
                        <div className="claw-add-im-summary-desc">
                          {imEnabled ? 'Enabled' : 'Disabled'}
                        </div>
                      </div>
                    </div>
                  ) : null}
                </div>

                {error ? (
                  <div className="claw-add-im-error-banner">
                    <AlertCircle className="claw-add-im-error-icon" strokeWidth={1.9} />
                    <span>{error}</span>
                  </div>
                ) : null}

                {activeStep === 'defaults' ? (
                  <div className="claw-add-im-panel">
                    <div className="claw-add-im-section-title">Connection defaults</div>
                    <p className="claw-add-im-section-desc">
                      Controls the sidebar name for this IM and the default model and workspace it uses.
                    </p>
                    <div className="claw-add-im-form-grid is-two">
                      <label className="claw-add-im-field">
                        <span className="claw-add-im-field-label">Agent name</span>
                        <input
                          className="claw-add-im-input"
                          value={agentProfile.name}
                          onChange={(event) =>
                            onUpdateAgentProfile({ name: event.target.value })
                          }
                          placeholder={`${installTargetLabel(officialInstallTarget)} Agent`}
                        />
                      </label>
                      <label className="claw-add-im-field">
                        <span className="claw-add-im-field-label">Short description</span>
                        <input
                          className="claw-add-im-input"
                          value={agentProfile.description}
                          onChange={(event) =>
                            onUpdateAgentProfile({ description: event.target.value })
                          }
                          placeholder="Example: Answers project questions in the Feishu chat"
                        />
                      </label>
                    </div>
                    <div className="claw-add-im-form-grid is-two">
                      <label className="claw-add-im-field">
                        <span className="claw-add-im-field-label">Model</span>
                        <select
                          className="claw-add-im-input"
                          value={channelModel}
                          onChange={(event) => onSetChannelModel(event.target.value)}
                        >
                          <option value="auto">auto</option>
                          <option value="deepseek-v4-pro">deepseek-v4-pro</option>
                        </select>
                      </label>
                      <label className="claw-add-im-field">
                        <span className="claw-add-im-field-label">Connection enabled</span>
                        <div className="claw-add-im-toggle-row">
                          <span>{channelEnabled ? 'Enabled' : 'Disabled'}</span>
                          <ToggleSwitch
                            checked={channelEnabled}
                            onChange={onSetChannelEnabled}
                            ariaLabel="Toggle connection enabled"
                          />
                        </div>
                      </label>
                    </div>
                    <label className="claw-add-im-field">
                      <span className="claw-add-im-field-label">Workspace override</span>
                      <input
                        className="claw-add-im-input"
                        value={channelWorkspaceRoot}
                        onChange={(event) => onSetChannelWorkspaceRoot(event.target.value)}
                        placeholder="Optional. Enter a custom working directory"
                      />
                      <span className="claw-add-im-field-hint">
                        If left empty, this IM uses the default working directory:
                      </span>
                      <span className="claw-add-im-workspace-preview">{DEFAULT_WORKSPACE_PREVIEW}</span>
                    </label>
                  </div>
                ) : null}

                {activeStep === 'prompt' ? (
                  <div className="claw-add-im-panel">
                    <div className="claw-add-im-section-title">Agent prompt profile</div>
                    <p className="claw-add-im-section-desc">
                      These instructions are injected into new requests from this connection.
                    </p>
                    <div className="claw-add-im-prompt-grid">
                      {AGENT_TABS.map((tab) => (
                        <label key={tab.id} className="claw-add-im-prompt-card">
                          <span className="claw-add-im-prompt-card-title">{tab.label}</span>
                          <span className="claw-add-im-prompt-card-helper">{tab.helper}</span>
                          <textarea
                            className="claw-add-im-textarea"
                            value={agentProfile[tab.id]}
                            onChange={(event) =>
                              onUpdateAgentProfile({ [tab.id]: event.target.value })
                            }
                            placeholder={tab.placeholder}
                          />
                        </label>
                      ))}
                    </div>
                  </div>
                ) : null}

                {activeStep === 'connection' ? (
                  <div className="claw-add-im-connection-layout">
                    <div className="claw-add-im-panel">
                      <div className="claw-add-im-section-title">Connection method</div>
                      <p className="claw-add-im-section-desc">
                        This integration uses a real platform authorization QR. After the platform scan succeeds, the desktop bridge returns the credentials or account binding.
                      </p>
                      <div className="claw-add-im-chip-row">
                        <span className="claw-add-im-chip">Official QR</span>
                        <span className="claw-add-im-chip is-mono">appId</span>
                        <span className="claw-add-im-chip is-mono">appSecret</span>
                      </div>
                      {provider !== 'weixin' ? (
                        <div className="claw-add-im-target-block">
                          <div className="claw-add-im-field-label">Authorization target</div>
                          <p className="claw-add-im-field-hint">
                            Feishu (mainland) and Lark (international) share the same integration path. Choose the environment you want to authorize here.
                          </p>
                          <div className="claw-add-im-target-tabs">
                            {installTargets.map((target) => (
                              <button
                                key={target}
                                type="button"
                                className={`claw-add-im-target-tab${
                                  officialInstallTarget === target ? ' is-active' : ''
                                }`}
                                onClick={() => onSetOfficialInstallTarget(target)}
                              >
                                {installTargetLabel(target)}
                              </button>
                            ))}
                          </div>
                        </div>
                      ) : null}
                      <ol className="claw-add-im-guide-list">
                        {selectedOption.guideSteps.map((step, index) => (
                          <li key={step} className="claw-add-im-guide-item">
                            <span className="claw-add-im-guide-index">{index + 1}</span>
                            <span>{step}</span>
                          </li>
                        ))}
                      </ol>
                      <div className="claw-add-im-info-strip">
                        <AlertCircle className="claw-add-im-info-icon" strokeWidth={1.9} />
                        <span>
                          This panel shows official QR authorization status. After binding, this platform gets its own sidebar connection. The local webhook is still available for optional external relays.
                        </span>
                      </div>
                    </div>

                    <div className="claw-add-im-qr-panel">
                      {installQrStatus === 'idle' ? (
                        <button
                          type="button"
                          className="claw-add-im-btn-primary"
                          onClick={onGenerateQr}
                        >
                          <QrCode className="claw-add-im-btn-icon" strokeWidth={1.9} />
                          Generate official QR
                        </button>
                      ) : null}
                      {installQrStatus === 'loading' ? (
                        <div className="claw-add-im-qr-state">
                          <Loader2 className="claw-add-im-qr-spinner is-spin" strokeWidth={2} />
                          <span>Generating QR…</span>
                        </div>
                      ) : null}
                      {installQrStatus === 'showing' || installQrStatus === 'success' ? (
                        <div className="claw-add-im-qr-frame">
                          <MockQrCode />
                        </div>
                      ) : null}
                      <div className="claw-add-im-qr-caption">Official authorization QR</div>
                      {installQrStatus === 'showing' ? (
                        <div className="claw-add-im-qr-meta">
                          <span>Expires in {installQrTimeLeft}s</span>
                          {installQrUserCode ? (
                            <span className="claw-add-im-qr-code">Code {installQrUserCode}</span>
                          ) : null}
                          <span>Confirm authorization on your phone and this will bind automatically.</span>
                        </div>
                      ) : null}
                      {installQrStatus === 'success' ? (
                        <div className="claw-add-im-qr-success">
                          <CheckCircle2 className="claw-add-im-qr-success-icon" strokeWidth={1.9} />
                          Scan succeeded
                        </div>
                      ) : null}
                      {installQrStatus === 'error' ? (
                        <div className="claw-add-im-qr-error-wrap">
                          <div className="claw-add-im-qr-error">
                            {installQrError || 'QR flow failed'}
                          </div>
                          <button type="button" className="claw-add-im-btn-secondary" onClick={onGenerateQr}>
                            Generate again
                          </button>
                        </div>
                      ) : null}
                    </div>

                    <div className="claw-add-im-panel">
                      <button
                        type="button"
                        className="claw-add-im-advanced-toggle"
                        onClick={() => onSetAdvancedOpen(!advancedOpen)}
                      >
                        <span className="claw-add-im-advanced-toggle-copy">
                          <span className="claw-add-im-section-title is-compact">Advanced settings</span>
                          <span className="claw-add-im-section-desc is-compact">
                            Webhook, run mode, secret, and relay payload
                          </span>
                        </span>
                        {advancedOpen ? (
                          <ChevronDown className="claw-add-im-advanced-chevron" strokeWidth={1.9} />
                        ) : (
                          <ChevronRight className="claw-add-im-advanced-chevron" strokeWidth={1.9} />
                        )}
                      </button>
                      {advancedOpen ? (
                        <div className="claw-add-im-advanced-body">
                          <div className="claw-add-im-advanced-card">
                            <div className="claw-add-im-section-title is-compact">Enable IM webhook</div>
                            <p className="claw-add-im-section-desc is-compact">
                              Built-in Feishu / Lark direct connections do not depend on the local webhook. Change this only when you also use an external relay or forwarder.
                            </p>
                            <div className="claw-add-im-form-grid is-two">
                              <label className="claw-add-im-field">
                                <span className="claw-add-im-field-label">Webhook</span>
                                <div className="claw-add-im-toggle-row">
                                  <span>{imEnabled ? 'Enabled' : 'Disabled'}</span>
                                  <ToggleSwitch
                                    checked={imEnabled}
                                    onChange={onSetImEnabled}
                                    ariaLabel="Toggle webhook"
                                  />
                                </div>
                              </label>
                              <label className="claw-add-im-field">
                                <span className="claw-add-im-field-label">Run mode</span>
                                <select
                                  className="claw-add-im-input"
                                  value={runMode}
                                  onChange={(event) => onSetRunMode(event.target.value)}
                                >
                                  <option value="agent">agent</option>
                                  <option value="plan">plan</option>
                                </select>
                              </label>
                            </div>
                            <div className="claw-add-im-form-grid is-two">
                              <label className="claw-add-im-field">
                                <span className="claw-add-im-field-label">Port</span>
                                <input
                                  type="number"
                                  className="claw-add-im-input"
                                  value={imPort}
                                  onChange={(event) => onSetImPort(Number(event.target.value))}
                                />
                              </label>
                              <label className="claw-add-im-field">
                                <span className="claw-add-im-field-label">Path</span>
                                <input
                                  className="claw-add-im-input"
                                  value={imPath}
                                  onChange={(event) => onSetImPath(event.target.value)}
                                />
                              </label>
                            </div>
                            <div className="claw-add-im-form-grid is-split">
                              <label className="claw-add-im-field">
                                <span className="claw-add-im-field-label">Response timeout (seconds)</span>
                                <input
                                  type="number"
                                  className="claw-add-im-input"
                                  value={responseTimeoutSec}
                                  onChange={(event) =>
                                    onSetResponseTimeoutSec(Number(event.target.value))
                                  }
                                />
                              </label>
                              <label className="claw-add-im-field">
                                <span className="claw-add-im-field-label">Webhook secret</span>
                                <div className="claw-add-im-secret-row">
                                  <input
                                    type={showSecret ? 'text' : 'password'}
                                    className="claw-add-im-secret-input"
                                    value={secret}
                                    onChange={(event) => onSetSecret(event.target.value)}
                                  />
                                  <button
                                    type="button"
                                    className="claw-add-im-secret-toggle"
                                    onClick={onToggleShowSecret}
                                    aria-label={showSecret ? 'Hide value' : 'Show value'}
                                  >
                                    {showSecret ? (
                                      <EyeOff className="claw-add-im-secret-toggle-icon" />
                                    ) : (
                                      <Eye className="claw-add-im-secret-toggle-icon" />
                                    )}
                                  </button>
                                </div>
                              </label>
                            </div>
                          </div>
                          <div className="claw-add-im-advanced-card">
                            <div className="claw-add-im-binding-head">
                              <div>
                                <div className="claw-add-im-section-title is-compact">Binding payload</div>
                                <p className="claw-add-im-section-desc is-compact">
                                  The payload never includes platform credentials. Keep bot tokens, secrets, AES keys, and similar values only in the relay or platform app configuration.
                                </p>
                              </div>
                              <button
                                type="button"
                                className="claw-add-im-btn-secondary"
                                onClick={onCopyBinding}
                              >
                                {copied ? (
                                  <CheckCircle2 className="claw-add-im-copy-icon is-success" strokeWidth={1.9} />
                                ) : (
                                  <Copy className="claw-add-im-copy-icon" strokeWidth={1.9} />
                                )}
                                {copied ? 'Copied' : 'Copy binding payload'}
                              </button>
                            </div>
                            <div className="claw-add-im-binding-grid">
                              <div>
                                <div className="claw-add-im-summary-kicker">Webhook endpoint</div>
                                <div className="claw-add-im-endpoint-box">{endpoint}</div>
                                <div className="claw-add-im-summary-kicker claw-add-im-binding-payload-label">
                                  Payload
                                </div>
                                <textarea
                                  readOnly
                                  className="claw-add-im-binding-textarea"
                                  value={MOCK_BINDING_PAYLOAD}
                                />
                              </div>
                              <div className="claw-add-im-binding-notes">
                                <div className="claw-add-im-info-strip">
                                  <AlertCircle className="claw-add-im-info-icon" strokeWidth={1.9} />
                                  <span>
                                    No webhook secret is set, so the relay can post directly to the local endpoint.
                                  </span>
                                </div>
                                <div className="claw-add-im-info-strip">
                                  <AlertCircle className="claw-add-im-info-icon" strokeWidth={1.9} />
                                  <span>
                                    Built-in Feishu / Lark direct connections do not depend on the local webhook. Change this only when you also use an external relay or forwarder.
                                  </span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      ) : null}
                    </div>
                  </div>
                ) : null}
              </>
            )}
          </div>
        </div>

        <footer className="claw-add-im-dialog-footer">
          <div className="claw-add-im-footer-hint">
            {isManageSelection
              ? 'Choose a connected IM to open its settings'
              : `Step ${activeStepIndex + 1} / ${DIALOG_STEPS.length} · ${activeStepConfig.description}`}
          </div>
          <div className="claw-add-im-footer-actions">
            {!isManageSelection && mode === 'edit' && existingChannel ? (
              <button type="button" className="claw-add-im-btn-danger">
                <Trash2 className="claw-add-im-btn-icon" strokeWidth={1.9} />
                Delete IM
              </button>
            ) : null}
            <button type="button" className="claw-add-im-btn-secondary" onClick={onClose}>
              Cancel
            </button>
            {activeStepIndex > 0 && !isManageSelection ? (
              <button type="button" className="claw-add-im-btn-secondary" onClick={onPrevStep}>
                Previous
              </button>
            ) : null}
            <button
              type="button"
              className="claw-add-im-btn-primary"
              disabled={busy && !isManageSelection}
              onClick={onPrimaryAction}
            >
              {busy && !isManageSelection ? (
                <Loader2 className="claw-add-im-btn-icon is-spin" strokeWidth={2} />
              ) : null}
              {primaryActionLabel}
            </button>
          </div>
        </footer>
      </div>
    </div>
  )
}

function previewInitialState(mode: ClawAddImDialogPreviewMode): {
  dialogMode: ClawImDialogMode
  manageStage: ClawManageStage
  activeStep: ClawDialogStep
  channels: ClawImChannelSidebarSnapshot[]
  selectedChannelId: string
  provider: ClawImProvider
  installQrStatus: ClawInstallQrStatus
  installQrTimeLeft: number
  installQrUserCode: string
  installQrError: string
  error: string | null
  busy: boolean
  advancedOpen: boolean
} {
  if (mode === 'manage') {
    return {
      dialogMode: 'edit',
      manageStage: 'select',
      activeStep: 'defaults',
      channels: PREVIEW_CHANNELS,
      selectedChannelId: 'feishu-team',
      provider: 'feishu',
      installQrStatus: 'idle',
      installQrTimeLeft: 0,
      installQrUserCode: '',
      installQrError: '',
      error: null,
      busy: false,
      advancedOpen: false,
    }
  }
  if (mode === 'edit') {
    return {
      dialogMode: 'edit',
      manageStage: 'configure',
      activeStep: 'defaults',
      channels: PREVIEW_CHANNELS,
      selectedChannelId: 'feishu-team',
      provider: 'feishu',
      installQrStatus: 'success',
      installQrTimeLeft: 0,
      installQrUserCode: '',
      installQrError: '',
      error: null,
      busy: false,
      advancedOpen: false,
    }
  }
  if (mode === 'empty') {
    return {
      dialogMode: 'add',
      manageStage: 'select',
      activeStep: 'defaults',
      channels: PREVIEW_CHANNELS,
      selectedChannelId: '',
      provider: 'feishu',
      installQrStatus: 'idle',
      installQrTimeLeft: 0,
      installQrUserCode: '',
      installQrError: '',
      error: null,
      busy: false,
      advancedOpen: false,
    }
  }
  if (mode === 'manageEmpty') {
    return {
      dialogMode: 'edit',
      manageStage: 'select',
      activeStep: 'defaults',
      channels: [],
      selectedChannelId: '',
      provider: 'feishu',
      installQrStatus: 'idle',
      installQrTimeLeft: 0,
      installQrUserCode: '',
      installQrError: '',
      error: null,
      busy: false,
      advancedOpen: false,
    }
  }
  return {
    dialogMode: 'add',
    manageStage: 'select',
    activeStep:
      mode === 'prompt'
        ? 'prompt'
        : mode === 'connection' ||
            mode === 'qrLoading' ||
            mode === 'qrShowing' ||
            mode === 'qrSuccess' ||
            mode === 'qrError'
          ? 'connection'
          : 'defaults',
    channels: [],
    selectedChannelId: 'feishu-team',
    provider: 'feishu',
    installQrStatus:
      mode === 'qrLoading'
        ? 'loading'
        : mode === 'qrShowing'
          ? 'showing'
          : mode === 'qrSuccess'
            ? 'success'
            : mode === 'qrError'
              ? 'error'
              : 'idle',
    installQrTimeLeft: mode === 'qrShowing' ? 87 : 0,
    installQrUserCode: mode === 'qrShowing' ? 'ABCD-1234' : '',
    installQrError:
      mode === 'qrError'
        ? 'WeChat login service is unavailable. Restart the app and try again.'
        : '',
    error: mode === 'error' ? 'Could not save IM connection settings.' : null,
    busy: mode === 'busy',
    advancedOpen: mode === 'connection',
  }
}

/** Full-screen preview shell for ?clawAddImDialogPreview URL hooks. */
export function ClawAddImDialogPreview({
  mode,
}: {
  mode: ClawAddImDialogPreviewMode
}): ReactElement {
  const initial = useMemo(() => previewInitialState(mode), [mode])
  const [dialogMode] = useState(initial.dialogMode)
  const [manageStage, setManageStage] = useState(initial.manageStage)
  const [activeStep, setActiveStep] = useState(initial.activeStep)
  const [selectedChannelId, setSelectedChannelId] = useState(initial.selectedChannelId)
  const [provider] = useState(initial.provider)
  const [installQrStatus, setInstallQrStatus] = useState(initial.installQrStatus)
  const [installQrTimeLeft] = useState(initial.installQrTimeLeft)
  const [installQrUserCode] = useState(initial.installQrUserCode)
  const [installQrError] = useState(initial.installQrError)
  const [advancedOpen, setAdvancedOpen] = useState(initial.advancedOpen)
  const [channelModel, setChannelModel] = useState('auto')
  const [channelEnabled, setChannelEnabled] = useState(true)
  const [channelWorkspaceRoot, setChannelWorkspaceRoot] = useState('')
  const [officialInstallTarget, setOfficialInstallTarget] = useState<ClawInstallTarget>('feishu')
  const [imEnabled, setImEnabled] = useState(true)
  const [runMode, setRunMode] = useState('agent')
  const [imPort, setImPort] = useState(8787)
  const [imPath, setImPath] = useState('/claw/im')
  const [responseTimeoutSec, setResponseTimeoutSec] = useState(120)
  const [secret, setSecret] = useState('')
  const [showSecret, setShowSecret] = useState(false)
  const [copied, setCopied] = useState(false)
  const [agentProfile, setAgentProfile] = useState<ClawAgentProfile>({
    name: 'feishu agent',
    description: '',
    identity: '',
    personality: '',
    userContext: '',
    replyRules: '',
  })

  const endpoint = `http://127.0.0.1:${imPort}${imPath.startsWith('/') ? imPath : `/${imPath}`}`
  const channels =
    mode === 'empty'
      ? PREVIEW_CHANNELS
      : mode === 'manageEmpty'
        ? []
        : dialogMode === 'edit'
          ? PREVIEW_CHANNELS
          : []

  const onPrimaryAction = (): void => {
    if (dialogMode === 'edit' && manageStage === 'select') {
      setManageStage('configure')
      return
    }
    const stepIndex = DIALOG_STEPS.findIndex((step) => step.id === activeStep)
    if (stepIndex < DIALOG_STEPS.length - 1) {
      setActiveStep(DIALOG_STEPS[stepIndex + 1].id)
    }
  }

  return (
    <ClawAddImDialogView
      mode={dialogMode}
      manageStage={manageStage}
      activeStep={activeStep}
      provider={provider}
      channels={channels}
      selectedChannelId={selectedChannelId}
      agentProfile={agentProfile}
      channelModel={channelModel}
      channelEnabled={channelEnabled}
      channelWorkspaceRoot={channelWorkspaceRoot}
      officialInstallTarget={officialInstallTarget}
      advancedOpen={advancedOpen}
      imEnabled={imEnabled}
      runMode={runMode}
      imPort={imPort}
      imPath={imPath}
      responseTimeoutSec={responseTimeoutSec}
      secret={secret}
      showSecret={showSecret}
      endpoint={endpoint}
      copied={copied}
      installQrStatus={installQrStatus}
      installQrTimeLeft={installQrTimeLeft}
      installQrUserCode={installQrUserCode}
      installQrError={installQrError}
      error={initial.error}
      loadingConfig={false}
      busy={initial.busy}
      onClose={() => undefined}
      onSelectStep={setActiveStep}
      onEnterManageConfigure={(channelId) => {
        setSelectedChannelId(channelId)
        setManageStage('configure')
      }}
      onReturnToManageSelection={() => setManageStage('select')}
      onUpdateAgentProfile={(patch) => setAgentProfile((prev) => ({ ...prev, ...patch }))}
      onSetChannelModel={setChannelModel}
      onSetChannelEnabled={setChannelEnabled}
      onSetChannelWorkspaceRoot={setChannelWorkspaceRoot}
      onSetOfficialInstallTarget={setOfficialInstallTarget}
      onSetAdvancedOpen={setAdvancedOpen}
      onSetImEnabled={setImEnabled}
      onSetRunMode={setRunMode}
      onSetImPort={setImPort}
      onSetImPath={setImPath}
      onSetResponseTimeoutSec={setResponseTimeoutSec}
      onSetSecret={setSecret}
      onToggleShowSecret={() => setShowSecret((value) => !value)}
      onCopyBinding={() => {
        setCopied(true)
        window.setTimeout(() => setCopied(false), 1600)
      }}
      onGenerateQr={() => setInstallQrStatus('showing')}
      onPrevStep={() => {
        const stepIndex = DIALOG_STEPS.findIndex((step) => step.id === activeStep)
        if (stepIndex > 0) setActiveStep(DIALOG_STEPS[stepIndex - 1].id)
      }}
      onPrimaryAction={onPrimaryAction}
    />
  )
}

type ClawAddImDialogProductionProps = {
  mode: ClawImDialogMode
  onClose: () => void
}

/** Production claw-route IM dialog with mock snapshots for visual parity. */
export function ClawAddImDialogProduction({
  mode,
  onClose,
}: ClawAddImDialogProductionProps): ReactElement {
  const [manageStage, setManageStage] = useState<ClawManageStage>(
    mode === 'edit' ? 'select' : 'select',
  )
  const [activeStep, setActiveStep] = useState<ClawDialogStep>('defaults')
  const [selectedChannelId, setSelectedChannelId] = useState(
    () => CLAW_SIDEBAR_PRODUCTION_CHANNELS[0]?.id ?? '',
  )
  const [provider] = useState<ClawImProvider>('feishu')
  const [installQrStatus, setInstallQrStatus] = useState<ClawInstallQrStatus>('idle')
  const [advancedOpen, setAdvancedOpen] = useState(false)
  const [channelModel, setChannelModel] = useState('auto')
  const [channelEnabled, setChannelEnabled] = useState(true)
  const [channelWorkspaceRoot, setChannelWorkspaceRoot] = useState('')
  const [officialInstallTarget, setOfficialInstallTarget] = useState<ClawInstallTarget>('feishu')
  const [imEnabled, setImEnabled] = useState(true)
  const [runMode, setRunMode] = useState('agent')
  const [imPort, setImPort] = useState(8787)
  const [imPath, setImPath] = useState('/claw/im')
  const [responseTimeoutSec, setResponseTimeoutSec] = useState(120)
  const [secret, setSecret] = useState('')
  const [showSecret, setShowSecret] = useState(false)
  const [copied, setCopied] = useState(false)
  const [agentProfile, setAgentProfile] = useState<ClawAgentProfile>({
    name: 'feishu agent',
    description: '',
    identity: '',
    personality: '',
    userContext: '',
    replyRules: '',
  })

  const endpoint = `http://127.0.0.1:${imPort}${imPath.startsWith('/') ? imPath : `/${imPath}`}`
  const channels = mode === 'edit' ? CLAW_SIDEBAR_PRODUCTION_CHANNELS : []

  const onPrimaryAction = (): void => {
    if (mode === 'edit' && manageStage === 'select') {
      setManageStage('configure')
      return
    }
    const stepIndex = DIALOG_STEPS.findIndex((step) => step.id === activeStep)
    if (stepIndex < DIALOG_STEPS.length - 1) {
      setActiveStep(DIALOG_STEPS[stepIndex + 1].id)
    }
  }

  return (
    <ClawAddImDialogView
      mode={mode}
      manageStage={manageStage}
      activeStep={activeStep}
      provider={provider}
      channels={channels}
      selectedChannelId={selectedChannelId}
      agentProfile={agentProfile}
      channelModel={channelModel}
      channelEnabled={channelEnabled}
      channelWorkspaceRoot={channelWorkspaceRoot}
      officialInstallTarget={officialInstallTarget}
      advancedOpen={advancedOpen}
      imEnabled={imEnabled}
      runMode={runMode}
      imPort={imPort}
      imPath={imPath}
      responseTimeoutSec={responseTimeoutSec}
      secret={secret}
      showSecret={showSecret}
      endpoint={endpoint}
      copied={copied}
      installQrStatus={installQrStatus}
      installQrTimeLeft={0}
      installQrUserCode=""
      installQrError=""
      error={null}
      loadingConfig={false}
      busy={false}
      onClose={onClose}
      onSelectStep={setActiveStep}
      onEnterManageConfigure={(channelId) => {
        setSelectedChannelId(channelId)
        setManageStage('configure')
      }}
      onReturnToManageSelection={() => setManageStage('select')}
      onUpdateAgentProfile={(patch) => setAgentProfile((prev) => ({ ...prev, ...patch }))}
      onSetChannelModel={setChannelModel}
      onSetChannelEnabled={setChannelEnabled}
      onSetChannelWorkspaceRoot={setChannelWorkspaceRoot}
      onSetOfficialInstallTarget={setOfficialInstallTarget}
      onSetAdvancedOpen={setAdvancedOpen}
      onSetImEnabled={setImEnabled}
      onSetRunMode={setRunMode}
      onSetImPort={setImPort}
      onSetImPath={setImPath}
      onSetResponseTimeoutSec={setResponseTimeoutSec}
      onSetSecret={setSecret}
      onToggleShowSecret={() => setShowSecret((value) => !value)}
      onCopyBinding={() => {
        setCopied(true)
        window.setTimeout(() => setCopied(false), 1600)
      }}
      onGenerateQr={() => setInstallQrStatus('showing')}
      onPrevStep={() => {
        const stepIndex = DIALOG_STEPS.findIndex((step) => step.id === activeStep)
        if (stepIndex > 0) setActiveStep(DIALOG_STEPS[stepIndex - 1].id)
      }}
      onPrimaryAction={onPrimaryAction}
    />
  )
}
